name: PROD app deploy

on:
  workflow_dispatch:
    inputs:
      release_version:
        type: string
        description: Release version
        required: true

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: us-east-1
      ENVIRONMENT: production

    steps:
    - name: Download release from S3
      run: aws s3 sync s3://totembound-releases . --exclude "*" --include "totem-app/release-${{ github.event.inputs.release_version }}.zip"

    - name: Unzip release
      working-directory: ./totem-app
      run: unzip release-${{ github.event.inputs.release_version }}.zip

    - name: Deploy to app S3 bucket
      working-directory: ./totem-app
      run: aws s3 sync build s3://totembound-app --delete

    - name: Invalidate CloudFront cache
      run: aws cloudfront create-invalidation --distribution-id E3TBCP5P18U4EE --paths "/*"
